import { chromium } from "/home/user/hidento/node_modules/playwright/index.mjs";
const D = process.argv[2];
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const q = await b.newPage({ viewport: { width: 1440, height: 900 }, deviceScaleFactor: 1.5 });
await q.goto("http://localhost:5199/#staff"); await q.waitForTimeout(3000);
const i = q.locator("input"); await i.nth(0).fill("demo_admin"); await i.nth(1).fill("Demo12345!"); await q.keyboard.press("Enter"); await q.waitForTimeout(5500);
await q.locator('button[aria-label="close"]').first().click().catch(() => {}); await q.waitForTimeout(500);
const go = async (h, w = 2500) => { await q.evaluate((x) => { location.hash = x; }, h); await q.waitForTimeout(w); };
await go("#staff/dashboard"); await q.screenshot({ path: `${D}/dashboard.png` });
await go("#staff/cases"); await q.screenshot({ path: `${D}/cases.png` });
await go("#staff/production"); await q.screenshot({ path: `${D}/production.png` });
await q.getByRole("button", { name: "مسح ملصق" }).click(); await q.waitForTimeout(800);
await q.locator(".fixed input").fill("1010"); await q.keyboard.press("Enter"); await q.waitForTimeout(2000);
await q.screenshot({ path: `${D}/scan.png` }); await q.keyboard.press("Escape"); await q.waitForTimeout(400);
await q.getByRole("button", { name: "رضا الأطباء" }).click(); await q.waitForTimeout(2000);
await q.screenshot({ path: `${D}/ratings.png` });
await go("#staff/accounts"); await q.getByRole("button", { name: "نقاط الولاء" }).click(); await q.waitForTimeout(2000);
await q.screenshot({ path: `${D}/loyalty.png` });
await go("#staff/invoices"); await q.screenshot({ path: `${D}/invoices.png` });
await go("#staff/cases"); await q.locator('table button[title="طباعة ملصق QR"]').first().click(); await q.waitForTimeout(1000);
await q.screenshot({ path: `${D}/label.png` }); await q.keyboard.press("Escape");
await go("#staff/settings"); await q.evaluate(() => { const el = [...document.querySelectorAll("h3")].find((h) => /الأتمتة/.test(h.textContent)); el?.scrollIntoView({ block: "start" }); window.scrollBy(0, -20); }); await q.waitForTimeout(800);
await q.screenshot({ path: `${D}/automations.png` });
await q.setViewportSize({ width: 390, height: 844 }); await go("#staff/cases"); await q.evaluate(() => window.scrollTo(0, 640)); await q.waitForTimeout(600);
await q.screenshot({ path: `${D}/m-cases.png` });
await b.close();
